spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    #远程规则
    remote:
      - 'https://github.tmby.shop/https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt' #AdGuard DNS filter
      - 'https://ghp.ci/https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt' #adguard
      - 'https://gitdl.cn/https://github.com/Potterli20/file/releases/download/ad-hosts-pro/ad-adguardhome.txt' #AdAway Default Blocklist
      - 'https://mirror.ghproxy.com/https://raw.githubusercontent.com/lingeringsound/10007_auto/master/all'
      - 'https://cdn.jsdelivr.net/gh/examplecode/ad-rules-for-xbrowser@master/core-rule-cn.txt'
      - 'https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt'  # anti
      - 'https://ghp.ci/raw.githubusercontent.com/8680/GOODBYEADS/master/data/rules/dns.txt'
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - 'mylist.txt'
  output:
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:    #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      adgh.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
#      regex.txt:
#        - REGEX
#      domain.txt:
#        - DOMAIN
#      modify.txt:
#        - MODIFY
