spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    #远程规则
    remote:
      - 'https://cdn.jsdelivr.net/gh/hoshsadiq/adblock-nocoin-list/hosts.txt'  #adblock-nocoin-list
      - 'https://cdn.jsdelivr.net/gh/durablenapkin/scamblocklist/adguard.txt' #Scam Blocklist
      - 'https://someonewhocares.org/hosts/zero/hosts' #Dan Pollock's List
      - 'https://cdn.jsdelivr.net/gh/AdguardTeam/FiltersRegistry/filters/filter_15_DnsFilter/filter.txt' #AdGuard DNS filter
      - 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext' #Peter Lowe's List
      - 'https://abp.oisd.nl/basic/' #OISD Blocklist Basic
      - 'https://adaway.org/hosts.txt' #AdAway Default Blocklist
      - 'https://cdn.jsdelivr.net/gh/crazy-max/WindowsSpyBlocker/data/hosts/spy.txt' #WindowsSpyBlocker
      - 'https://cdn.jsdelivr.net/gh/o0HalfLife0o/list@master/ad-pc.txt' #HalfLife（pc）
      - 'https://cdn.jsdelivr.net/gh/banbendalao/ADgk@master/ADgk.txt' #Adgk
      - 'https://cdn.jsdelivr.net/gh/VeleSila/yhosts/hosts.txt' #yhosts
      - 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts' #大圣净化
      #- 'https://gitlab.com/quidsup/notrack-blocklists/-/raw/master/trackers.list' #Domains classified as tracking or advertising
      - 'https://code.gitlink.org.cn/hacamer/AdRules/raw/branch/main/adguard-full.txt' #AdRules AdGuard Full List
      - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt'
      - 'https://raw.githubusercontent.com/2771936993/HG/main/hg1.txt'
      - 'https://mirror.ghproxy.com/https://raw.githubusercontent.com/2771936993/HG/main/yx.txt'
      - 'https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt'
      - 'https://raw.gitmirror.com/lingeringsound/adblock_auto/main/Rules/adblock_auto.txt'
      - 'https://github.tmby.shop/https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt'
      - 'http://rssv.cn/adguard/api.php?type=black'
      - 'https://mirror.ghproxy.com/raw.githubusercontent.com/Lynricsy/HyperADRules/master/rules.txt'
      - 'https://ad.yuwell.dynv6.net/adblock.txt'
      - 'https://mirror.ghproxy.com/https://raw.githubusercontent.com/lingeringsound/adblock_auto/main/Rules/adblock_auto.txt'
      - 'https://mirror.ghproxy.com/https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt'
      - 'https://raw.gitmirror.com/TTDNS/Cat/main/DNS.TXT'
      - 'https://gitdl.cn/https://github.com/Potterli20/file/releases/download/ad-hosts-pro/ad-adguardhome.txt'
      - 'https://raw.githubusercontent.com/8680/GOODBYEADS/master/rules.txt'
      - 'https://raw.githubusercontent.com/8680/GOODBYEADS/master/dns.txt'
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_21.txt'
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_37.txt'
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt'
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt'
      - 'https://file-git.trli.club/file-hosts/ad-hosts/hosts'
      - 'https://file-git.trli.club/file-hosts/ad-hosts/adblock'
      - 'https://mirror.ghproxy.com/https://raw.githubusercontent.com/2771936993/HG/main/yx.txt'
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - 'mylist.txt'
  output:
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:    #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      adgh.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
#      regex.txt:
#        - REGEX
#      domain.txt:
#        - DOMAIN
#      modify.txt:
#        - MODIFY
